<?php

namespace AdminBundle\Repository;

/**
 * CevaplarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CevaplarRepository extends \Doctrine\ORM\EntityRepository
{
}
