<?php

namespace AdminBundle\Repository;

/**
 * KategoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KategoriRepository extends \Doctrine\ORM\EntityRepository
{
}
