<?php

namespace AdminBundle\Repository;

/**
 * KategoriTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KategoriTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
