<?php

namespace AdminBundle\Repository;

/**
 * YetkilerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YetkilerRepository extends \Doctrine\ORM\EntityRepository
{
}
