normal_user_homepage:
    path:     /
    defaults: { _controller: NormalUserBundle:Default:index }

ticketEkle:
    path:     /ticketEkle
    defaults: { _controller: NormalUserBundle:Ticket:index }

ajax_ticketEkle :
    path:     /ajax-ticketEkle
    defaults: { _controller: NormalUserBundle:Ticket:ekle }

ajax_cozKabul:
    path:     /ajax-cozKabul
    defaults: { _controller: NormalUserBundle:Ticket:cozKabul }

ajax_cozReddet:
    path:     /ajax-cozReddet
    defaults: { _controller: NormalUserBundle:Ticket:cozRed }

